models/Book.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Url;
/**
 * This is the model class for table "{{%books}}".
 *
 * @property string $id
 * @property string $title
 * @property string $image
 * @property string $author_id
 * @property string $publisher_id
 * @property string $published_at
 *
 * @property Author $author
 * @property Publisher $publisher
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%books}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'author_id', 'publisher_id'], 'required'],
            [['author_id', 'publisher_id'], 'integer'],
            [['published_at'], 'default', 'value' => 1970],
            [['published_at'], 'date', 'format'=>'yyyy'],
            [['title', 'image'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Author::className(), 'targetAttribute' => ['author_id' => 'id']],
            [['publisher_id'], 'exist', 'skipOnError' => true, 'targetClass' => Publisher::className(), 'targetAttribute' => ['publisher_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'image' => 'Image',
            'imageFile' => 'Image',
            'author_id' => 'Author ID',
            'publisher_id' => 'Publisher ID',
            'published_at' => 'Published At',
        ];
    }
	
    /**
     * Delete image with model
     * @return bool
     */
    public function beforeDelete()
    {

        if (parent::beforeDelete()) {
			$file = Yii::getAlias('@webroot'). '/upload/images/' . $this->image;
            if ($this->image && file_exists($file))
                unlink($file);
            return true;
        } else {
            return false;
        }
    }
    /**
     * @return string Image Url
     */
    public function getImageUrl()
    {
        $file = Yii::getAlias('@webroot'). '/upload/images/' . $this->image;

        if (!$this->image || !is_file($file))
            $this->image = 'default.jpg';
        return Url::to('@web/upload/images/' . $this->image, true);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Author::className(), ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPublisher()
    {
        return $this->hasOne(Publisher::className(), ['id' => 'publisher_id']);
    }
}

controllers/AuthorsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Author;
use yii\web\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
class AuthorsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Creates a new Author model.
     * If creation is successful, the browser will be redirected to the 'main' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Author();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ['success' => true];
            }
            return $this->redirect('/');
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                ]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing Author model.
     * If update is successful, the browser will be redirected to the 'main' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ['success' => true];
            }
            return $this->redirect('/');
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                ]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Deletes an existing Author model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/']);
    }

    /**
     * Finds the Author model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Author the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/BooksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Book;
use app\models\UploadForm;
use app\models\BookSearch;
use yii\web\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BooksController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();
        $upload = new UploadForm();
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            if ($upload->validate()) {
                $file = Yii::getAlias('@webroot'). '/upload/images/' . md5(time()) . '.' . $upload->imageFile->extension;
                if ($upload->imageFile){
                    $upload->imageFile->saveAs($file);
                    $model->image = basename($file);
                }
                if ($model->save()) {
                    if (Yii::$app->request->isAjax) {
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return ['success' => true];
                    }
                    return $this->redirect('/');
                } else {
                    if (Yii::$app->request->isAjax) {
                        return $this->renderAjax('_form-ajax', [
                            'model' => $model,
                            'upload' => $upload,
                        ]);
                    } else {
                        return $this->render('update', [
                            'model' => $model,
                            'upload' => $upload,
                        ]);
                    }
                }
            }
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                    'upload' => $upload,
                ]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'upload' => $upload,
                ]);
            }
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $upload = new UploadForm();
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            
            if ($upload->validate()) {
                $file = Yii::getAlias('@webroot'). '/upload/images/' . md5(time()) . '.' . $upload->imageFile->extension;
                if ($upload->imageFile){
					$oldFile = Yii::getAlias('@webroot'). '/upload/images/' . $model->image;
					if ($model->image && file_exists($oldFile))
						unlink($oldFile);
                    $upload->imageFile->saveAs($file);
                    $model->image = basename($file);
                }
                if($model->save()){
                
                    if (Yii::$app->request->isAjax) {
                        Yii::$app->response->format = Response::FORMAT_JSON;
                        return ['success' => true];
                    }
                    return $this->redirect('/');
                } else {
                    if (Yii::$app->request->isAjax) {
                        return $this->renderAjax('_form-ajax', [
                            'model' => $model,
                            'upload' => $upload,
                        ]);
                    } else {
                        return $this->render('update', [
                            'model' => $model,
                            'upload' => $upload,
                        ]);
                    }
                }
            }
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                    'upload' => $upload,
                ]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'upload' => $upload,
                ]);
            }
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['success' => true];
        }
        return $this->redirect(['/']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/PublishersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Publisher;
use yii\web\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PublisherController implements the CRUD actions for Publisher model.
 */
class PublishersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Creates a new Publisher model.
     * If creation is successful, the browser will be redirected to the 'main' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Publisher();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ['success' => true];
            }
            return $this->redirect('/');
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                ]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing Publisher model.
     * If update is successful, the browser will be redirected to the 'main' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ['success' => true];
            }
            return $this->redirect('/');
        } else {
            if (Yii::$app->request->isAjax) {
                return $this->renderAjax('_form-ajax', [
                    'model' => $model,
                ]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Deletes an existing Publisher model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/']);
    }

    /**
     * Finds the Publisher model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Publisher the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Publisher::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/books/_form-ajax.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Author;
use app\models\Publisher;
/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title"><?=$model->isNewRecord ? 'Create' : 'Update'?> book</h4>
</div>
<div class="modal-body">
    <div class="book-form">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => "multipart/form-data"]]); ?>
        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'author_id')
            ->dropDownList(
                ArrayHelper::map(Author::find()->asArray()->all(), 'id', 'name')
            )
        ?>
        <?= $form->field($model, 'publisher_id')->dropDownList(
                ArrayHelper::map(Publisher::find()->asArray()->all(), 'id', 'name')
            )
        ?>
        <?= $form->field($model, 'published_at')->textInput() ?>
        <?= $form->field($upload, 'imageFile')->fileInput() ?>
        <?php if (!$model->isNewRecord) echo Html::img($model->getImageUrl(), ['style'=>'width: 150px; margin-bottom:15px']); ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/books/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Author;
use app\models\Publisher;
/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="book-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?=
    $form->field($model, 'author_id')
        ->dropDownList(
            ArrayHelper::map(Author::find()->asArray()->all(), 'id', 'name')
        )
    ?>
    <?=
    $form->field($model, 'publisher_id')
        ->dropDownList(
            ArrayHelper::map(Publisher::find()->asArray()->all(), 'id', 'name')
        )
    ?>
    <?= $form->field($model, 'published_at')->textInput() ?>
    <?= $form->field($upload, 'imageFile')->fileInput() ?>
    <?php if (!$model->isNewRecord) echo Html::img($model->getImageUrl(), ['style'=>'width: 150px; margin-bottom:15px']); ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/books/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $upload app\models\UploadForm */

$this->title = 'Create Book';
?>
<div class="book-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
        'upload' => $upload,
    ]) ?>
</div>

views/books/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\web\View;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Books';
?>
<div class="book-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Html::a('Create Book', '#', ['class'=>'btn btn-success', 'data-url' => Url::to(['books/create']), 'data-toggle' => 'modal', 'data-target' => '#modal']) ?>
    <?= Html::a('Create Author', '#', ['class'=>'btn btn-success', 'data-url' => Url::to(['authors/create']), 'data-toggle' => 'modal', 'data-target' => '#modal']) ?>
    <?= Html::a('Create Publisher', '#', ['class'=>'btn btn-success', 'data-url' => Url::to(['publishers/create']), 'data-toggle' => 'modal', 'data-target' => '#modal']) ?>

    <?php Pjax::begin(['id' => 'books-pjax', 'timeout' => 5000,'linkSelector' => 'a[data-pjax=1], th > a']); ?>
    <?= GridView::widget([
        'id' => 'books-pjax',
        'dataProvider' => $dataProvider,
		'layout'=>"<br/>{pager}<br/>{summary}<br/>{items}",
        'columns' => [
            [
                'attribute' => 'id',
                'headerOptions' => ['style' => 'width:50px']
            ],
            [
                'format' => 'html',
                'label' => 'Title',
                'value' => function ($data) {
                    return Html::a($data->title, ['books/update', 'id' => $data->id]) . '<br>' . Html::img($data->imageUrl, ['style' => 'width: 60px;']);
                },
            ],
            [
                'label' => 'Author',
                'attribute' => 'author.name',
            ],
            [
                'label' => 'Publisher',
                'attribute' => 'publisher.name',
            ],
            [
                'attribute' => 'published_at',
                'headerOptions' => ['style' => 'width:110px']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{upd} {delete}',
                'buttons'=>[
                    'upd'=>function ($url, $data) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', '#', ['data-url' => Url::to(['books/update', 'id' => $data->id]), 'data-toggle' => 'modal', 'data-target' => '#modal']);    
                    },
                   'delete'=>function ($url, $data) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', '#', ['data-url' => Url::to(['books/delete', 'id' => $data->id]),'class'=>'ajaxDelete']);    
                    }
                ],
                'headerOptions' => ['style' => 'width:50px']
            ],
        ],
    ]); ?>
<?php 
$this->registerJs("
    var modal = $('#modal');
    modal.modalForm();
    modal.on('ModalSubmit', function (event, data, status, xhr) {
        var contentType = xhr.getResponseHeader('content-type') || '';
        if (contentType.indexOf('json') > -1) {
            if (data.success){
                jQuery(this).modal('hide');
                jQuery.pjax({
                    push : true,
                    replace : false,
                    timeout : 5000,
                    scrollTo : false,
                    container : '#books-pjax'
                });
            }
        }
    });
    $('.ajaxDelete').on('click', function(e) {
        e.preventDefault();
        if (!confirm('Are you sure you want to delete this item?'))
            return;
        var deleteUrl = $(this).data('url');
        var pjaxContainer = 'books-pjax';
        $.ajax({
                url: deleteUrl,
                type: 'post',
                dataType: 'json',
                error: function(xhr, status, error) {
                    alert('There was an error with your request.' + xhr.responseText);
                }
        }).done(function(data) {
                $.pjax.reload({container: '#'+pjaxContainer });
        });                     
    });
", View::POS_READY);
Pjax::end(); ?>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

views/books/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $upload app\models\UploadForm */
$this->title = 'Update Book: ' . $model->title;
?>
<div class="book-update">
    <?= $this->render('_form', [
        'model' => $model,
        'upload' => $upload,
    ]) ?>
</div>